services:
  - type: worker
    name: kindy-bot
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
